export enum PreferenceSegment {
  BURGUER_TYPE = 'BURGUER_TYPE',
  DELIVERY = 'DELIVERY',
  LOCATION = 'LOCATION',
  PRICING = 'PRICING',
  SITE_TYPE = 'SITE_TYPE',
  INTOLERANCES = 'INTOLERANCES',
  HIGHLIGHTS = 'HIGHLIGHTS',
  GARNISH = 'GARNISH',
  MODE = 'MODE',
}
